service: servicio-vuelos-compras

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    COMPRAS_TABLE: ${self:service}-${self:provider.stage}-compras
    TOKENS_TABLE: servicio-vuelos-${self:provider.stage}-tokens  # Aquí defines la variable para la tabla tokens
  iam:
    role: arn:aws:iam::078729045663:role/LabRole

functions:
  crearCompra:
    handler: crearCompra.handler
    events:
      - http:
          path: /compras
          method: post
          cors: true
          integration: lambda

  obtenerCompras:
    handler: obtenerCompras.handler
    events:
      - http:
          path: /comprasGet
          method: post
          cors: true
          integration: lambda

  modificarCompra:
    handler: modificarCompra.handler
    events:
      - http:
          path: /compras
          method: put
          cors: true
          integration: lambda

  eliminarCompra:
    handler: eliminarCompra.handler
    events:
      - http:
          path: /compras
          method: delete
          cors: true
          integration: lambda

  obtenerCompraById:
    handler: obtenerCompraPorId.handler
    events:
      - http:
          path: /compras-id_compra
          method: post
          cors: true
          integration: lambda

  validarToken:
    handler: Lambda_ValidarTokenAcceso.lambda_handler
    runtime: python3.9
    events:
      - http:
          path: /usuarios/token/validar
          method: post
          cors: true
          integration: lambda
    environment:
      t_tokens_acceso: ${self:provider.environment.TOKENS_TABLE}

resources:
  Resources:
    ComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COMPRAS_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: id_compra
            AttributeType: S
          - AttributeName: fecha_compra
            AttributeType: S   # Usado para el LSI
          - AttributeName: precio_total
            AttributeType: S   # Usado para el GSI
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: id_compra
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

        # Índice Secundario Local (LSI)
        LocalSecondaryIndexes:
          - IndexName: FechaCompraIndex
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: fecha_compra
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        # Índice Secundario Global (GSI)
        GlobalSecondaryIndexes:
          - IndexName: EstadoIndex
            KeySchema:
              - AttributeName: precio_total
                KeyType: HASH
              - AttributeName: id_compra
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
